# These are supported funding model platforms

github: # Add GitHub Sponsors username here once set up
custom: ["https://github.com/mhamp1/quantum-falcon-cockp#support--sponsorship", "mailto:mhamp1trading@yahoo.com"]
