include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - prefer_final_fields
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - use_key_in_widget_constructors
    - prefer_typing_uninitialized_variables
    - prefer_collection_literals

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
