// Mocks generated by Mockito 5.4.4 from annotations
// in quantum_falcon_mobile/test/gamification_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:quantum_falcon_mobile/models/quest_model.dart' as _i6;
import 'package:quantum_falcon_mobile/models/streak_model.dart' as _i7;
import 'package:quantum_falcon_mobile/models/xp_model.dart' as _i5;
import 'package:quantum_falcon_mobile/services/api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: Duration.zero,
      ) as Duration);

  @override
  _i4.Future<_i5.XpModel> getXp() => (super.noSuchMethod(
        Invocation.method(
          #getXp,
          [],
        ),
        returnValue: _i4.Future<_i5.XpModel>.value(_i5.XpModel(
          currentXp: 0,
          level: 0,
          nextLevelXp: 0,
          totalXp: 0,
          lastUpdated: DateTime(2000),
        )),
      ) as _i4.Future<_i5.XpModel>);

  @override
  _i4.Future<_i5.XpAward> awardXp({
    required int? amount,
    required String? reason,
    required String? actionType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #awardXp,
          [],
          {
            #amount: amount,
            #reason: reason,
            #actionType: actionType,
          },
        ),
        returnValue: _i4.Future<_i5.XpAward>.value(_i5.XpAward(
          amount: 0,
          reason: '',
          actionType: '',
          timestamp: DateTime(2000),
        )),
      ) as _i4.Future<_i5.XpAward>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLeaderboard({
    int? limit = 100,
    String? period = r'all_time',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaderboard,
          [],
          {
            #limit: limit,
            #period: period,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<_i6.QuestListResponse> getQuests({String? category}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuests,
          [],
          {#category: category},
        ),
        returnValue:
            _i4.Future<_i6.QuestListResponse>.value(_i6.QuestListResponse(
          quests: <_i6.QuestModel>[],
          totalQuests: 0,
          completedQuests: 0,
        )),
      ) as _i4.Future<_i6.QuestListResponse>);

  @override
  _i4.Future<_i6.QuestModel> getQuestById(String? questId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestById,
          [questId],
        ),
        returnValue: _i4.Future<_i6.QuestModel>.value(_i6.QuestModel(
          id: '',
          title: '',
          description: '',
          category: _i6.QuestCategory.daily,
          xpReward: 0,
          target: 0,
        )),
      ) as _i4.Future<_i6.QuestModel>);

  @override
  _i4.Future<_i6.QuestModel> updateQuestProgress({
    required String? questId,
    required int? progress,
    bool? increment = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuestProgress,
          [],
          {
            #questId: questId,
            #progress: progress,
            #increment: increment,
          },
        ),
        returnValue: _i4.Future<_i6.QuestModel>.value(_i6.QuestModel(
          id: '',
          title: '',
          description: '',
          category: _i6.QuestCategory.daily,
          xpReward: 0,
          target: 0,
        )),
      ) as _i4.Future<_i6.QuestModel>);

  @override
  _i4.Future<Map<String, dynamic>> completeQuest(String? questId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeQuest,
          [questId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i7.StreakResponse> getStreaks() => (super.noSuchMethod(
        Invocation.method(
          #getStreaks,
          [],
        ),
        returnValue:
            _i4.Future<_i7.StreakResponse>.value(_i7.StreakResponse(
          streaks: <_i7.StreakModel>[],
          totalActiveStreaks: 0,
          lastUpdated: DateTime(2000),
        )),
      ) as _i4.Future<_i7.StreakResponse>);

  @override
  _i4.Future<_i7.StreakModel> getStreakByType(_i7.StreakType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakByType,
          [type],
        ),
        returnValue: _i4.Future<_i7.StreakModel>.value(_i7.StreakModel(
          currentStreak: 0,
          longestStreak: 0,
          streakStartDate: DateTime(2000),
          lastActivityDate: DateTime(2000),
          type: _i7.StreakType.dailyLogin,
          nextMilestone: 0,
        )),
      ) as _i4.Future<_i7.StreakModel>);

  @override
  _i4.Future<_i7.StreakModel> recordStreakActivity(_i7.StreakType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordStreakActivity,
          [type],
        ),
        returnValue: _i4.Future<_i7.StreakModel>.value(_i7.StreakModel(
          currentStreak: 0,
          longestStreak: 0,
          streakStartDate: DateTime(2000),
          lastActivityDate: DateTime(2000),
          type: _i7.StreakType.dailyLogin,
          nextMilestone: 0,
        )),
      ) as _i4.Future<_i7.StreakModel>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
